services:
  api:
    build:
      context: ../apps/kajovo-hotel-api
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/ready', timeout=3)"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build:
      context: ..
      dockerfile: apps/kajovo-hotel-web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1/healthz >/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
